---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watone-sjw-dx-web
  namespace: lajw
  labels:
    web: watone-sjw-dx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      web: watone-sjw-dx-web
  template:
    metadata:
      labels:
        web: watone-sjw-dx-web
    spec:
      nodeSelector:
        role2: worker
      imagePullSecrets:
        - name: image
      containers:
        - name: watone-sjw-dx-web
          image: reg.watone.local/lajw/watone-sjw-dx-web:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: watone-sjw-dx-web
  namespace: lajw
  labels:
    web: watone-sjw-dx-web
spec:
  type: NodePort
  ports:
    - name: watone-sjw-dx-web
      port: 3000
      targetPort: 3000
      nodePort: 33005
  selector:
    web: watone-sjw-dx-web